---
title: "Final Project"
author: "Luke O'Sullivan and Anand"
date: "November 6, 2016"
output: html_document
---

#GDP of Uganda, USA and Canada


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
country_data <- read.csv(file="data/gapminder.csv", header = TRUE)
uganda <- subset(country_data, country_data$country == "Uganda")
usa <- subset(country_data, country_data$country == "United States")
canada <- subset(country_data, country_data$country == "Canada")

plot(uganda$year, uganda$gdpPercap, xlab = "year", ylab = "GDP", main = "Uganda")
```

\n
*Uganda's GDP Increases upto 1970s , takes a dip in the 80s and then has been increasing after that. *
```{r echo=FALSE}
plot(usa$year, usa$gdpPercap, xlab = "year", ylab = "GDP", main = "USA")
```
\n

*USA's GDP has seen constant increases from the 50s to the 2000s.*
```{r echo=FALSE}
plot(canada$year, canada$gdpPercap, xlab = "year", ylab = "GDP", main = "Canada")
```


*Canada's GDP has seen constant increases from the 50s to the 2000s.*

##Life Expectancy values in each continent


```{r echo=FALSE,results='asis'}


cat("  \n  \n")
analyse <- function(cname)
{
  continent_data = subset(country_data, country_data$continent == cname)
  
  cat("The mean value of life expectancy for ",cname," is ",mean(continent_data$lifeExp),"years.  \n")
  cat("The minimum value of life expectancy is ",min(continent_data$lifeExp),"years.  \n")
  cat("The maximum value of life expectancy is ",max(continent_data[,5]),"years.  \n")
  }
cont_list = levels(country_data$continent)
for (c in cont_list)
{
  cat('----------------------------------------',c,'--------------------------------  \n')
  analyse (noquote(c))
  cat("\n")
}

```


```{r echo=FALSE}
hist(country_data$lifeExp, xlab = "life expectancy", ylab = "frequency of values", main="Histogram of global life expectancy")
sp <- c()
for (i in 20:90) {
  sp <- c(sp,i)
  i <- i+2
}
hist(country_data$lifeExp, xlab = "life expectancy", ylab = "frequency of values", main="Histogram of global life expectancy (bin size = 2)",breaks=sp)
cat("  \n\n")
```



*Looks like there are two peaks, one at 45, and one at ~72 years old.*

